add new !Cidr function
dvonessen/aws-cloudformation-yaml pull request #3
Opened 2018-03-09 21:34 UTC by tyron

2018-03-29 08:26 UTC, bitfoo1 requested changes
@tyron thank you for adding this awesome function. But please would you change mentioned comments. And maybe you are able to rebase to only one commit?
Thank you!

2018-03-29 08:26 UTC, dthielking commented on CHANGELOG.md
> +  * !GetCidr
!GetCidr -> !Cidr
As the original function in CFN.

2018-03-29 08:26 UTC, dthielking commented on README.md
> +    * __!GetCidr__
__!GetCidr__ -> !Cidr
See above.

2018-03-29 20:38 UTC, tyron commented
@dthielking I made the changes requested. However my very limited proficiency using git doesn't allow me to rebase to one commit. I failed in my attempts to squash it on my local machine.

2018-03-31 07:39 UTC, bitfoo1 approved these changes

2018-03-31 07:41 UTC, merged

2018-03-31 07:41 UTC, dthielking commented
@tyron thank you for fixing the documentation miss match. I squash merged this branch into master and will create new version.